Fixes #253: Use Spring 3 compatible param builder.
In case of using method introduced in spring 4.2, catch the
NoSuchMethodError and fall back to empty requestParam name/value.